version: "3"

volumes:
  postgres_data12:
  node_modules:
  packs:
  bundle_cache:

services:
  ###########################
  # SHARED POSTGRES CLUSTER #
  ###########################
  postgres:
    image: postgres:12
    volumes:
      - postgres_data12:/var/lib/postgresql/data
    logging:
      driver: "none"
    ports:
      - "5432:5432"

  ##############
  # BOT SERVER #
  ##############
  backend:
    build:
      context: ../bot_man
      dockerfile: ../bot_boot/Dockerfile-backend
    tty: true
    stdin_open: true
    env_file:
      - ./vars.env
      - ./bot_secret.env
    environment:
      - SKIP_YARN=true
      - REDIS_URL=redis://redis
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    links:
      - postgres
    volumes:
      - ../bot_man:/app:delegated
      - bundle_cache:/bundle

  frontend:
    build:
      context: ../bot_man_frontend
      dockerfile: ../bot_boot/Dockerfile-frontend
    tty: true
    stdin_open: true
    env_file:
      - ./vars.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    links:
      - backend
    volumes:
      - ../bot_man_frontend:/app:delegated
      - node_modules:/app/node_modules
